Algoritmo "soma"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
   L1: inteiro
   L2: inteiro
   area : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 
   escreva("Digite o Lado: ")
   leia(L1)
   
   escreva("Digite o Lado: ")
   leia(L2)
   escreva()
   area <- L1 + L2
   escreva("O cálculo da área é: ", area)

Fimalgoritmo