Algoritmo "soma"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
   NUM: inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 
   escreva("Digite um número: ")
   leia(NUM)
   
   se (NUM % 2 = 0) então
     escreva("Número par")
   senão
     escreva("Número ímpar")
   fimse
   
Fimalgoritmo