Algoritmo "soma"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
   NUM: real
   RESTO: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 
   escreva("Digite um número: ")
   leia(NUM)
   escreva()
   
   RESTO <- num mod 2
   escreva("O resto da divisão é: ", RESTO)
   
Fimalgoritmo